server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        server:
          webflux:
            routes:
              - id: products-route
                uri: lb://catalog-service
                predicates:
                  - Path=/products/**
                filters:
                  - StripPrefix=0
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
