server:
  port: 8082

spring:
  application:
    name: basket-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/basketdb
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true