server:
  port: 8761
spring:
  application:
    name: discovery-server
  cloud:
    compatibility-verifier:
      enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
